import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="he" dir="rtl">
            <body>
                <header>
                    <nav
                        style={{
                            display: 'flex',
                            gap: '1rem',
                            justifyContent: 'center',
                            padding: '1rem',
                        }}
                    >
                        <Link href="/">בית</Link>
                        <Link href="/academy">אקדמיה</Link>
                        <Link href="/apps">אפליקציות</Link>
                        <Link href="/services">שירותים</Link>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    )
}
