import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { MainNavbar } from '@shared'
import type { Metadata } from 'next'
import { Assistant } from 'next/font/google'
import './globals.css'

const assistant = Assistant()

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="he" dir="rtl">
            <body className={assistant.className}>
                <AppRouterCacheProvider>
                    <header>
                        <MainNavbar />
                    </header>
                    {children}
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
